// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcout

type Country struct {
	CountryISO2 string `json:"countryISO2"`
	CountryName string `json:"countryName"`
}

type SwiftCode struct {
	SwiftCode   string `json:"swiftCode"`
	Address     string `json:"address"`
	BankName    string `json:"bankName"`
	CountryISO2 string `json:"countryISO2"`
}
